### ISSUE TITLE
feature : official 64bit support in osx

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#2016]
Success condition is either:
* "My mac 64-bit" scheme in XCode
* "osx 64bit" as an option in Project Generator

**Comment by kylemcdonald** [comment]
i just read through this thread and #3039 and couldn't get any of the forks people have worked on over the last year to work for me. i even made some basic changes that should have fixed things that have changed since the forks stopped development (assuming the libraries were good). i consider myself pretty ok at getting OF to work, but i didn't realize it was still this hard to build 64-bit for OSX!

so, it looks like the status is: there are a few forks, from @openframeworks (february 4 2014), @NickHardeman (march 12 2014), and @prisonerjohn (january 4 2015). but as far as i can tell, none of these are going to be merged into master. instead, support will come from apothecary formulas and eventually some changes to the OF project, XCode project template, and makefiles.

a few questions:

1. @obviousjim as the issue-assignee, can you say whether this is about right?
2. if openFrameworks/feature-64bit is not going to be merged, can we delete the branch to avoid confusion?
3. is it possible to merge apothecary formulas with updated libs before they cover all platforms? for example it would be good to get people who are using master to check OSX 64bit even if windows isn't ready yet.
4. is there a list somewhere of the apothecary coverage overall, so people who want to help finish can write more formulas? i feel like i saw this somewhere once but can't find it now. maybe @bakercp?

**Comment by armadillu** [comment]
Yeah lets try to all row in the same direction; so hard to keep up

**Comment by danoli3** [comment]
I have a Travis-CI Apothecary script building Repo that lists the OS X side as well as iOS formulas in their build status: https://github.com/danoli3/apothecary-den

# Build Status:

| Lib                             | osx |  ios | 
|---------------------------------|-----|-------|
| FreeImage                       |[![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=freeimage-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=freeimage-osx) | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=freeimage-ios)](https://travis-ci.org/danoli3/apothecary-den?branch=freeimage-ios) |
| FreeType                        |[![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=freetype-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=freetype-osx) | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=freetype-ios)](https://travis-ci.org/danoli3/apothecary-den?branch=freetype-ios) | 
| tess2                           | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=tess2-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=tess2-osx) | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=tess2-ios)](https://travis-ci.org/danoli3/apothecary-den?branch=tess2-ios)| 
| poco                            |[![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=poco-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=poco-osx) | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=poco-ios)](https://travis-ci.org/danoli3/apothecary-den?branch=poco-ios) | 
| openssl                         | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=openssl-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=openssl-osx) | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=openssl-ios)](https://travis-ci.org/danoli3/apothecary-den?branch=openssl-ios)| 
| ofxAssimpModelLoader -> assimp  |[![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=assimp-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=assimp-osx) | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=assimp-ios)](https://travis-ci.org/danoli3/apothecary-den?branch=assimp-ios) |
| ofxOpenCV -> opencv             | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=opencv-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=opencv-osx) | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=opencv-ios)](https://travis-ci.org/danoli3/apothecary-den?branch=opencv-ios) |
| glew                            | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=glew-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=glew-osx)| N/A | 
| glfw                            | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=glfw-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=glfw-osx) | N/A |
| glu                             | N/A | N/A   |
| glut                            | ✗   | N/A | 
| cairo                          | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=cairo-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=cairo-osx) |  N/A  |
| kiss                            | N/A  |  N/A | 
| portaudio                       | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=fmod-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=fmod-osx) |  N/A |
| fmodex                            | ✓?  | N/A  | 
| rtAudio                         | [![Build Status](https://travis-ci.org/danoli3/apothecary-den.svg?branch=rtaudio-osx)](https://travis-ci.org/danoli3/apothecary-den?branch=rtaudio-osx)  |  N/A | 


----------------------------------

This doesn't show complete coverage though, Table is built from a full coverage type found in the Apothecary directory.

**Comment by kylemcdonald** [comment]
@danoli3 thanks so much, that is super helpful for giving me an idea about where we are. "passing" means that both 32 bit and 64 bit are compiling, or is it just that the formula doesn't have any errors for whatever it's doing at the moment?

**Comment by danoli3** [comment]
So the passing means it is successfully compiling the static libraries for i386 libstdc++ and x86_64 libc++ (64bit) for OS X. (And i386, x86_64, armv7 and arm64 for iOS).

This gives a good indication of where the libraries are at, however not the complete story.
For example; With iOS it had heaps of Symbolic link errors at linking stage with DEBUG mode due to some strange scope issues the libraries had (i.e. using the DEBUG preprocessor internally https://github.com/pocoproject/poco/issues/544 ). I've fixed these at the core of those libraries now, however this the the testing that will be required in the next stage for 0.9.

**Comment by kylemcdonald** [comment]
@danoli3 awesome. i also see now in https://github.com/openframeworks/openFrameworks/pull/3453#issuecomment-70859846 that @ofTheo already encouraged the idea of merging formulas before they have complete coverage. good to see.

**Comment by danoli3** [comment]
@kylemcdonald Yeah master has all of the latest Apothecary Formulas we currently have.
Strategy was Strip any pull requests for Apothecary with static libs/updated headers, to just the core scripts themselves using cherry-pick.

So from now on, any new Apothecary formula updates / PR's:
Make sure to just have the pure apothecary script changes only.

PR's with static libs + updated headers can come in later in separate PR's. 
(This decoupling has made building it all much easier as their was many inter script dependancies, especially for all the android scripts, and Poco + OpenSSL for all).

**Comment by obviousjim** [comment]
@kylemcdonald currently @prisonerjohn's fork of OF works on Windows and OS X, We are using it for projects right now on both OS's. What issues did you find in compiling it?

I lost track of understanding the complexities of merging this when it became dependent on Apothecary and c++ 11. @elliotwoods and @bakercp are more up to date on this aspect. But my vote is for getting whatever issues kyle is finding finding merged into the OF 64 branch, fixed up and publish how to get it running somewhere.

**Comment by tgfrerer** [comment]
hey @danoli3 i've tested glew on os x and it seems to build fine for me, is it possible that the travis build stage fails at `clean()` because the travis system doesn't copy the files upon `copy` ?

**Comment by danoli3** [comment]
@tgfrerer Yeah the Copy part is failing due to: 
``rm: libs/glew/include: No such file or directory```

Will just need to add ```rm -rf``` (remove if exists) to fix this.

**Comment by tgfrerer** [comment]
I found out something quite exciting: **clang can make fat libs with the correct -stdlib and -stdc++ in one go, while compiling**! 

Since this might speed up & simplify generating apothecary scripts considerably, i've put my findings into a gist. It contains the words "vanilla" and "fat", but not "ice cream":

https://gist.github.com/tgfrerer/8e2d973ed0cfdd514de6

I'll do some more testing on this tomorrow, but the initial fat libs i got were quite promising. I'm putting this up now so that folks in other time zones with more clang fu and linking experience might want to check up on it whilst i catch up on sleep.

**Comment by kylemcdonald** [comment]
going to un-assign @obviousjim for on this issue now. still :heart: you, just want to open up the spot in case someone else wants to take the lead on this :)

@tgfrerer that's amazing, i would love to hear @danoli3 and @bakercp on this.

also, regarding my effort to get 64-bit compiling, it ended up working with @prisonerjohn's branch. i just had to craft a project file that was correct. using a pretty standard project file i saw this from ofApp:

```
ld: warning: ignoring file /Users/kyle/Documents/openFrameworks/libs/openFrameworksCompiled/lib/osx/openFrameworks.a, file was built for archive which is not the architecture being linked (i386): /Users/kyle/Documents/openFrameworks/libs/openFrameworksCompiled/lib/osx/openFrameworks.a
Undefined symbols for architecture i386:
  "ofSoundBuffer::operator[](unsigned long)", referenced from:
      ofBaseSoundInput::audioIn(ofSoundBuffer&) in main.o
      ofBaseSoundOutput::audioOut(ofSoundBuffer&) in main.o
  "ofSetupOpenGL(int, int, ofWindowMode)", referenced from:
      _main in main.o
  "ofRunApp(ofBaseApp*)", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

i was a bit confused about why it mentioned ofSound objects... but this made me realize the ofApp was still building as i386 somehow.i looked in the build settings it said "Native architecture (x86_64)" but i switched it to "64-bit Intel (x86_64)" just for fun. it worked! then i switched it back to "Native" and it worked this time.

so it was a one-toggle switch but i'm not clear why it wasn't working with the original option, some kind of object file cache that needed to be cleaned and rebuilt?

**Comment by pizthewiz** [comment]
> I found out something quite exciting: clang can make fat libs with the correct -stdlib and -stdc++ in one go, while compiling!

Definitely a great find and could simplify the build process, but I wonder if some of the dependencies use their own build systems such that we aren't providing the actual args and arg ordering?

**Comment by bakercp** [comment]
@pizthewiz Yes, definitely an awesome find, but indeed many of the packages are using their own libs, settings, etc and it's sometimes difficult to modify a build system (e.g. Poco e.g. https://github.com/pocoproject/poco/issues/680).

**Comment by danomatika** [comment]
Also, how will this work with the iOS simulator? Does the iPad 2 simulator use 32 bit (matching iPad arch) or 64 bit libs (matching OS X)? If so, it may not be as easy as saying 32 bit iOS libs are C++ and 64 bit are C++11. I don't know but I thought I'd throw that out there.

**Comment by pizthewiz** [comment]
> Also, how will this work with the iOS simulator?

The iOS simulator uses the libs paired to the target device arch - simulating the iPhone 5, a 32-bit `armv7s` device, will use 32-bit `i386` libs and simulating an iPad Air, a 64-bit `arm64` device, will use 64-bit `x86_64` libs.

**Comment by danomatika** [comment]
... so that means we need i386 libs with both C++ & C++11 std libs? From what it seems like, if you want to use OF 0.9.0 with C++11 on an iPhone 5, you'll be linking to the i386 libs.

**Comment by pizthewiz** [comment]
> if you want to use OF 0.9.0 with C++11 on an iPhone 5, you'll be linking to the i386 libs.

Just to be a little more clear, if you wanted to _simulate_ an iPhone 5 in the iOS Simulator, you'd be using the `i386` slice of libs - on device, it would use the `armv7` slice. The `i386` libs used for the iOS Simulator and those for OS X are separate though - does iOS _need_ anything but `libc++` and C++11?

/cc @danoli3

**Comment by danomatika** [comment]
They are separate, yes (i.e. iOS fat libs include both arm and Mac arch). I'm just asking to make sure we don't miss this point and lead to link errors etc down the road. Best to double check. There are a number of add ons which include precompiled static libs. At the last there will need to be a large, loud note in the CHANGELOG about recompiling old static libs for C++11 ... unless they work fine with the ld stdlib. I'm not 100% sure either way.

**Comment by danoli3** [comment]
@danomatika Yeah iOS libs use their own iOS SDK version of the i386 and x86_64 which is lipo'd into the static fat lib. This fat lib is all compiled with libc++ C++11 (i386, x86_64, armv7, arm64)

Definitely need to add to the changelog all the information about this for libc++ for iOS
Libc++ and libstdc++ are not compatible at all. For example the size of core types like strings are different and will usually be the first place of a crash or not able to link.
Currently the core re-uses the OS X i386 for some of the simulator libraries, however these are using the OSX SDK and not the iOS SDK (which can cause incompatibility issues (main one I've found is min iOS target issues)). So we will have to make sure developers realise they can't re-use these two, especially for 0.9+ with the i386 being libstdc++ for OS X and iOS being libc++ for i386.

All static addon libraries that include libs for the simulator will need to be recompiled anyway to support x86_64 as well so as long as they realise the libc++ for iOS this should be okay for both simulator libs.

Just to clarify:
iPhone 5 simulator in debug mode will be linked against the iOS ```i386```
iPhone 5 simulator in release mode will be linked against the iOS ```x86_64``` (by default, unless build active architecture is set to YES), then ```i386```.

iPhone 6 simulator in debug/release mode will be linked against the iOS ```x86_64```

**Comment by pizthewiz** [comment]
> Currently the core re-uses the OS X i386 for some of the simulator libraries

Ahh interesting, it won't blow up statically linking to libs with different settings?

> iPhone 5 simulator in release mode will be linked against the iOS x86_64 (by default, unless build active architecture is set to YES), then i386.

The iPhone 5 runs an Apple A7 `ARMv7s` so I'm pretty sure the simulator and device will only ever run `i386` and `ARMv7` libs respectively. The 64-bit devices/simulator can run 32-bit libs, but not the other way around, no?

**Comment by danoli3** [comment]
Yeah it would blow up, I've made changes to remove this problem in my
current 0.9.0 ios branch, by making it link only to iOS fat libs, I'll PR
that core changes today like the OSX PR.

And it is strange thing with the new Xcode 6 for release mode for using a
lib that should be using i386 will use x86_64 (by default).
When previously this was not the case.
Anyway that is fixed by build active Architechures to YES.

**Comment by bilderbuchi** [comment]
closed by #3627, afaict.

**Comment by kylemcdonald** [comment]
:)

@danoli3 i noticed that https://github.com/danoli3/apothecary-den still shows "unknown" for port audio and rtAudio, is this actually a problem or just something that's out of date?

**Comment by ofTheo** [comment]
@kylemcdonald rtAudio has been built and updated for OS X.

**Comment by danoli3** [comment]
@kylemcdonald Updated apothecary-den to latest, all there now as well and passing

**Comment by kylemcdonald** [comment]
@danoli3 it looks like now poco says "error" and portaudio "unknown"... maybe just a glitch with travis timeouts for poco though?
