### ISSUE TITLE
ofxOsc compile error - VS 2015

### ISSUE THREAD

**Issue by charlesveasey** [openframeworks/openFrameworks#4097]
ofxOsc not compiling with master and VS 2015. 

1) compiler failed at logical "or" instead of the "II" 
2) function name conflict with PocoNetmdd.lib

Resolved with 2 commits:

https://github.com/charlesveasey/openFrameworks/commit/0fd621e0bce9dce51f856af0774838b6c058dd10

https://github.com/charlesveasey/openFrameworks/commit/ab63e9bfd8b151e426e67f3139dfb1d0e77b921d

**Comment by DomAmato** [comment]
+1 I had this same issue

**Comment by arturoc** [comment]
can you send a PR?

**Comment by charlesveasey** [comment]
https://github.com/openframeworks/openFrameworks/pull/4099

**Comment by bakercp** [comment]
See also https://github.com/openframeworks/openFrameworks/issues/3986

**Comment by bakercp** [comment]
@bilderbuchi I'd argue that this is a bug / regression that should be fixed before 0.9.0.

**Comment by arturoc** [comment]
btw, doesn't poco use namespace? how can it clash then?

**Comment by charlesveasey** [comment]
Also:
http://forum.openframeworks.cc/t/networkinitializer-duplicate-symbol-ofxosc-with-new-poco/18122/2

**Comment by arturoc** [comment]
ugh, ok i see, that's really a bug in poco and we should solve it there. i can try to recompile it. can you send your PR without the change to NetworkInitializer?

**Comment by charlesveasey** [comment]
New PR: https://github.com/openframeworks/openFrameworks/pull/4108

**Comment by arturoc** [comment]
closed by #4108

**Comment by charlesveasey** [comment]
I still have the NetworkInitializer name conflict with PocoNetmdd.lib. Were the POCO libs updated?
