### ISSUE TITLE
Code Signing for Mac Apps

### ISSUE THREAD

**Issue by kimasendorf** [openframeworks/openFrameworks#4421]
Probably not a real issue, but since it works nice for iOS apps it would be nice to be able to code sign Mac apps. Maybe it is just an account issue cause we are using an Enterprise account.
However Xcode 7 doesn't compile when I add an Apple ID.

> Command /usr/bin/codesign failed with exit code 1

**Comment by bilderbuchi** [comment]
ping @openframeworks/macos . Is this/can it be a bug on our side?

**Comment by ofTheo** [comment]
@kimasendorf did you make sure to sign both the openFrameworks and ofApp builds? 

can you test outside of Xcode by doing these steps?

```
codesign -f -s <signature> <path> -r="host => anchor apple and identifier com.apple.translate designated => identifier <BundleIdentifier>"
```
from: http://wiki.lazarus.freepascal.org/Code_Signing_for_Mac_OS_X

**Comment by armadillu** [comment]
Hey, not sure how directly related, but had some sandboxing/codeSigning woes recently. Sharing for any other coming across the same issue.

But on recent master, I found that building a debug OSX app and sending it to someone else (my computer has all sandbox stuff deactivated) makes the app crash when 2-clicked from the Finder. 

The crash report shows loading files from the filesystem being the cause, SIGABRT I believe. When launching the app from terminal (```/appDebug.app/Contents/macOS/appDebug```) all worked fine... so it felt somehow related to sandboxing.

So messing around the Xcode project, I found that disabling code signing entirely fixes the crash.

![screen shot 2017-04-12 at 10 54 16](https://cloud.githubusercontent.com/assets/167057/24964151/743331b0-1f6e-11e7-8656-411a81f734de.PNG)

**Comment by ofZach** [comment]
that's great to know -- I recently had issues with this as well (and we have had issues with this on the PG that we fixed using some roundabout hacks -- on first launch with sierra you basically find OF for us).  If it's helpful I discovered this is because of app translocation: 

http://lapcatsoftware.com/articles/app-translocation.html
https://eclecticlight.co/2016/06/16/macos-sierra-will-break-many-installers-and-updaters/

which runs untrusted code (typically zips that you download) in read only random locations and the apps get disconnected from their local files. 

my solution for my client was to suggest moving the .app to the desktop and back which removes this annoying attribute from the file but your solution seems much better.  

Maybe we can add this to the template?  cc @ofTheo

**Comment by ofZach** [comment]
ps: this break almost everything! -- p5 apps, electron apps, etc.  I think one other solution  (don't know how hard this is or what it entails) is to used signed disk images instead of zips...

**Comment by ofTheo** [comment]
Nice find!
We could add it to the template though maybe not the one which allows deployment to the app store as that needs code signing.

**Comment by armadillu** [comment]
So the whole thing feels quite random, it was still failing on some computers but not all. In the end, I'm doing this and seems to work on all computers -

Create a text file with something along these lines:

```
#/bin/bash
cd `dirname $0`
./YourApp.app/Contents/MacOS/YourApp
```

and name it ```start.command```. Place it besides your app. Make the file/script has executable permissions by setting them to 755:
```
$ chmod 755 start.command
```

And ask the end user to 2-click the ```start.command``` file instead of your App binary. This seems override Apple's Gatekeeper. 

One (maybe?) drawback to keep in mind is that this will start terminal.app, and all the app's console output will be printed in that window.
