### ISSUE TITLE
Quaternion Product implementation is incorrect

### ISSUE THREAD

**Issue by Poofjunior** [openframeworks/openFrameworks#4458]
In ofQuaternion.cpp [here](https://github.com/openframeworks/openFrameworks/blob/ac32f4d21ec54577298f5f9ad7636623ee3c441d/libs/openFrameworks/math/ofQuaternion.h), the second line of the multiplication operator is
    
     rhs._v.w*_v.y - rhs._v.x*_v.z + rhs._v.y*_v.w + rhs._v.z*_v.x,
    
but it should be
    
     rhs._v.w*_v.y + rhs._v.x*_v.z + rhs._v.y*_v.w - rhs._v.z*_v.x,
    
according to the definition. (See [this page](http://people.csail.mit.edu/bkph/articles/Quaternions.pdf) for the definition)

It's just one minus sign, but the net result is that multiplying two quaternions and then retrieving the resultant's angle-and-axis will always flip the sign on the y-axis.

I'm guessing that this will fix: https://github.com/openframeworks/openFrameworks/issues/785

**Comment by danoli3** [comment]
Wow nice find!! 
Could you do a Pull Request with the fix?

**Comment by bilderbuchi** [comment]
ping @memo who tidied this up last.

**Comment by Poofjunior** [comment]
Ok, here's the pull request!
https://github.com/openframeworks/openFrameworks/pull/4461

As a heads-up, this will likely change the expected output of the quaternionArcballExample such that the ball will appear to rotate on a coordinate frame that is fixed to the Arcball rather than giving the impression that the viewport is scrolling around the arcball.

I think the way to redo this example would involve creating an ofCamera, affixing a vector from the origin to that camera, and then rotating the camera with a quaternion. (I can generate this example if need be.)

**Comment by memo** [comment]
Hmmm, yea see @arturoc comment in the pull request. I wouldn't have touched the maths. That was from OSG. Which is still showing the same as OF
https://github.com/openscenegraph/osg/blob/master/include/osg/Quat#L194
