### ISSUE TITLE
ofSetColor doesn't work when light is enable

### ISSUE THREAD

**Issue by youandhubris** [openframeworks/openFrameworks#4684]
As posted [here](https://forum.openframeworks.cc/t/problem-with-lighting-and-3d-shapes-in-openframeworks-9/21803), ofSetColor doesn't  work when light is enabled.

As an example, you can quickly check the cameraParentingExample on the master branch, where every object stays blank.

**Comment by arturoc** [comment]
is this still an issue? i'm getting the correct behaviour in both osx and linux with this code:

```
class ofApp{
    ofEasyCam cam;
    ofLight light;

    void setup(){
        ofEnableLighting();
        ofEnableDepthTest();
        light.setup();
        light.enable();
        light.setPosition(-200,200,200);
    }

    void draw(){
        cam.begin();
        ofSetColor(255,0,0);
        ofDrawBox(0,0,0,100);
        cam.end();
    }
```

![screenshot from 2016-02-15 10-50-40](https://cloud.githubusercontent.com/assets/48240/13045132/fb973c44-d3d1-11e5-82cf-1543ea64f84d.png)

**Comment by youandhubris** [comment]
The issue seems to be the second and subsequent calls of ofSetColor. If I do something like this:

```
class ofApp{
    ofEasyCam cam;
    ofLight light;

    void setup(){
        ofEnableLighting();
        ofEnableDepthTest();
        light.setup();
        light.enable();
        light.setPosition(-200,200,200);
    }

    void draw(){
        cam.begin();

        ofSetColor(255,0,0);
        ofDrawBox(0,0,0,100);
        ofSetColor(0,0,255);
        ofDrawBox(0,100,100,100);

        cam.end();
    }
};
```

I get this: 
![screen shot 2016-02-15 at 11 10 36](https://cloud.githubusercontent.com/assets/5417523/13047115/cfdf8018-d3d4-11e5-84de-7fa898ea30a6.png)

I'm testing on OSX, both 092 and Master.

**Comment by leozimmerman** [comment]
I'm also having problems also with coloured meshes:

```
class ofApp{
    ofEasyCam cam;
    ofLight light;
    ofMesh mesh;

    void setup(){
        ofEnableLighting();
        ofEnableDepthTest();
        light.setup();
        light.enable();
        light.setPosition(-200,200,200);

          vector<ofFloatColor> cols;
          for (int i=0; i<15; i++){
               ofFloatColor c = ofFloatColor(ofColor::green);
               cols.push_back(c);
              ofVec3f pos = ofVec3f(0,-100,100);
              ofVec3f vec = pos + ofVec3f(ofRandom(-50,50), ofRandom(-50,50), ofRandom(-50,50));
              mesh.addVertex(vec);
            }
           mesh.addColors(cols);
    }

    void draw(){
        cam.begin();

        ofSetColor(255,0,0);
        ofDrawBox(0,0,0,100);
        ofSetColor(0,0,255);
        ofDrawBox(0,100,100,100);

        mesh.draw();

        cam.end();
    }
};
```

![screen shot 2016-02-15 at 14 42 17](https://cloud.githubusercontent.com/assets/3408646/13056249/f7d1efac-d3f2-11e5-9136-2f31b4d9d99e.png)


I don't know exactly why, but, replacing this lines in ofGLRenderer.cpp seems to make it right: 

```
void ofGLRenderer::setColor(int r, int g, int b, int a){
    currentStyle.color.set(r,g,b,a);
    glColor4f(r/255.f,g/255.f,b/255.f,a/255.f);
    if(lightingEnabled && !materialBound){
        glEnable(GL_COLOR_MATERIAL);
        #ifndef TARGET_OPENGLES
			glColorMaterial(GL_FRONT_AND_BACK, GL_AMBIENT_AND_DIFFUSE);
			//glColorMaterial(GL_FRONT, GL_AMBIENT_AND_DIFFUSE);
                       //glColorMaterial(GL_BACK, GL_AMBIENT_AND_DIFFUSE);
        #endif
        glEnable(GL_COLOR_MATERIAL);
    }
}
```
![screen shot 2016-02-15 at 14 46 31](https://cloud.githubusercontent.com/assets/3408646/13056357/9794e242-d3f3-11e5-8508-69ed1d3b9cdc.png)

Tested in OSX 10.10.5 with 0.9.3 branch

**Comment by arturoc** [comment]
This is solved in the 0.9.3 branch but please test since i was getting different results than you in some cases both with linux and an older version of osx

**Comment by leozimmerman** [comment]
Working fine now for me. (OSX 10.10.5). Thanks

**Comment by youandhubris** [comment]
On 093, still not working for me. OSX 10.11.3.

**Comment by firmread** [comment]
I tried:
```
class ofApp{
    ofEasyCam cam;
    ofLight light;

    void setup(){
        ofEnableLighting();
        ofEnableDepthTest();
        light.setup();
        light.enable();
        light.setPosition(-200,200,200);
    }

    void draw(){
        cam.begin();

        ofSetColor(255,0,0);
        ofDrawBox(0,0,0,100);
        ofSetColor(0,0,255);
        ofDrawBox(0,100,100,100);

        cam.end();
    }
};
```
still getting this:
<img width="388" alt="screen shot 2016-02-17 at 12 15 04 am" src="https://cloud.githubusercontent.com/assets/1666992/13100535/2ce1e43a-d50c-11e5-9ed6-4df658e999b0.png">

on both for master & 0.9.3
I'm also on OS X 10.11.3
