### ISSUE TITLE
Qt Creator Mac: Error parsing ofApp.qbs

### ISSUE THREAD

**Issue by c-mendoza** [openframeworks/openFrameworks#5572]
The error is:
```
(...)/openFrameworks/libs/openFrameworksCompiled/project/qtcreator/ofApp.qbs:35: error: TypeError: Result of expression 'CORE.includes' [undefined] is not an object.
```

Which means that no apps can be compiled. It seems like the problem began in [this commit].(https://github.com/openframeworks/openFrameworks/commit/62346e0f5f6c25fb24650adf31bb6743d7f95787)

I would love to help, but unfortunately I'm new at Qt Creator.

**Comment by arturoc** [comment]
can you check if my last commit fixes this?

**Comment by c-mendoza** [comment]
It doesn't parse out of the box. It complains about minimumOsxVersion not being a string, but that is solved by just putting it in quotes (line 51 in openFrameworks.qbs).

After fixing that, compilation and linking completes, but the binary produced is called "($PRODUCT_NAME).app" (literally... the variable name does not expand), and the .app produced is not runnable (it has the strikethrough on its app icon).

**Comment by c-mendoza** [comment]
Also, neither libfmodex.dylib nor the Resources folder are copied to the app bundle.

**Comment by bakercp** [comment]
I now have this problem with the latest commit:

![example__master__-_qt_creator](https://cloud.githubusercontent.com/assets/300484/25450942/29893ea2-2a86-11e7-8b97-b4f309889364.png)

**Comment by Daandelange** [comment]
I figured out that's because of newer qt versions that now depreciate `cpp.minimumOsxVersion` in favour of `cpp.minimumMacosVersion`. Also it has to be a string, not a number. (add apostrophes around the value)

Still that does not resolve the `$PRODUCT_NAME` error... _( using`Qt Creator 4.3.1, Based on Qt 5.9.1 (Clang 7.0 (Apple), 64 bit` )_

**Comment by bakercp** [comment]
When I apply the fixes mentioned above by @Daandelange, it begins to compile for me and I get 
![ofconstants_h___volumes_superfasthd_openframeworks_libs_openframeworks_utils___testqt___master__-_qt_creator_and_qt_creator_mac__error_parsing_ofapp_qbs_ _issue__5572_ _openframeworks_openframeworks](https://user-images.githubusercontent.com/300484/29296868-9a45dbf8-8122-11e7-8ca5-4656642e057b.png)

I also get the `PRODUCT_NAME` warnings.  I'm using the same version of Qt Creator as @Daandelange  above.

**Comment by bakercp** [comment]
Just to go further, `unordered_map` should be included with c++11, which is set in `ofApp.qbs` and `openFrameworks.qbs` and those vars are defined in `modules/of/of.qbs`, but it doesn't seem to be picking up the correct c++11 value ...

```
    cpp.cxxStandardLibrary: of.coreCxxStandardLibrary
    cpp.cxxLanguageVersion: of.coreCxxLanguageVersion
```

**Comment by bakercp** [comment]
Just a few more notes on this ...
![c___code_model_inspector_and_ofapp_qbs___volumes_superfasthd_openframeworks_libs_openframeworkscompiled_project_qtcreator___testqt___master__-_qt_creator](https://user-images.githubusercontent.com/300484/29297262-5c1513b4-8125-11e7-83a1-d532306d14d7.png)

**Comment by Daandelange** [comment]
Hmm, weird, I haven't got anything like your errors. Maybe there's something with lib STD missing ? Did you set the qt kit's compiler to use `/usr/bin/clang++` ? (sometimes I had to reconfigure a kit switching from other QT Creator versions (4.1).

Another side note: The errors shown @bakercp 's image _26th April_ referring to (`PRODUCT_NAME`) can partially be fixed pressing reset here (bottom right): 
![PRODUCT_NAME error Qt](https://user-images.githubusercontent.com/1329784/29426618-7f9c617a-8387-11e7-8681-d6f2ef4a1031.png)

Further more, I can add that at a given moment I had to manually add `curl`, using the following lines in my `testQt.qbs` : (see screenshot below)
```
        // general compilation fixes for OF0.9 + OSX 10.12
        Properties {
            condition: qbs.targetOS.contains("osx")
            of.linkerFlags: outer.concat([
                '-L'+Helpers.normalize(FileInfo.joinPaths(sourceDirectory,"../../../libs/curl/lib/osx/")),
                '-lcurl'
            ]);
        }
````
Then I get it to build and compile but the packaging / deploy /run step fails. The app packages in different sub dirs and `PRODUCT_NAME` still appears in the "Generated files". See screenshot below.
![Weird OF packaging in Qt](https://user-images.githubusercontent.com/1329784/29426864-426d2202-8388-11e7-8ffc-ec1259a06ed3.png)

I'm not sure this is still related to the same (initial) issue.
Moreover we're using an unsupported Qt version while this is the only version I get the current OF master to compile with.
But anyways, it would be great to get Qt working again on current master. :)

**Comment by bakercp** [comment]
OK, a few updates from here to get it to match with yours:

1. With 4.3 installed, delete my ~/.config/QtProject folder.
2. Run `openFrameworks/scripts/qtcreator/install_template.sh` script.
3. Open Qt Creator 4.3.
4. Open preferences and make sure my default 

_The automatically detected defaults that DON'T work ..._

![preferences](https://user-images.githubusercontent.com/300484/29472660-6fcb8ec2-841a-11e7-8d85-e0777236fd2d.png)

_The updated version that does compile ..._

![preferences](https://user-images.githubusercontent.com/300484/29472685-8a332310-841a-11e7-99fa-762743c48aff.png)

5. Then create a new project.
6. Modify the project.qbs to include the curl linker / include flags block as you noted. **This should be added to the base App qbs, I suspect.** 

Then compile.  Everything compiles and I get to the same point as you do with the mis-named $(PRODUCT_NAME) executable and the fmod dynlib is not copied.

Right now my main problem is understanding the mechanics of how QT qbs build system works -- I'm unable to find any references to $(PRODUCT_NAME).

Additionally the release target fails -- I believe that it fails because it can't find 64bit release for libopenframeworks.a.  But that's just a first guess.

**Comment by bakercp** [comment]
P.S. I'd also really like to get this working because I'm teaching OF in all of my courses this fall and would like to use Qt Creator if at all possible. :)

**Comment by bakercp** [comment]
Also, I'm accumulating fixes here:

https://github.com/openframeworks/openFrameworks/pull/5728

Please feel free to add to that PR / checklist. etc.

**Comment by bakercp** [comment]
QT is now working on macos 10.13 with the latest master branch.  Closing this. Thanks @arturoc

**Comment by arturoc** [comment]
It was actually @i-n-g-o who fixed this a while ago in https://github.com/openframeworks/openFrameworks/pull/5813
