### ISSUE TITLE
mismatch detected for '_ITERATOR_DEBUG_LEVEL'

### ISSUE THREAD

**Issue by chriship** [openframeworks/openFrameworks#6050]
With OF 0.10.0 in Visual Studio I keep getting issues regarding the _ITERATOR_DEBUG_LEVEL when I switch between Debug and Release and I have to rebuild the whole solution to get it to run.

Has anyone else come across this issue?

**Comment by fred-dev** [comment]
Me to, I delete the obj folder, seems to be something with vs 2017, does not happen with 2015.

**Comment by michaelbaisch** [comment]
Having the same problem. Deleting the obj folder helps, but it's a bit uncomfortable.

**Comment by chriship** [comment]
I believe this is fixed by doing the following in VS:

- Right-click project and select 'properties'
- Go to C/C++ and Output Files
- Set 'Object File Name' to $(IntDir)

**Comment by hiroMTB** [comment]
I wrote details and temporary solution for this issue on forum here.
https://forum.openframeworks.cc/t/solution-for-force-clean-rebuild-after-build-configuration-change-on-vs2017/30022

@arturoc 
This is the one I mentioned in ofxBerlin.
One of serious painful problem should be fixed asap imo.

**Comment by hiroMTB** [comment]
See also
https://github.com/openframeworks/projectGenerator/issues/159

**Comment by hiroMTB** [comment]
and this PR.
https://github.com/openframeworks/openFrameworks/pull/5655

**Comment by arturoc** [comment]
@hiroMTB do you mean that PR introduced the problem?

**Comment by hiroMTB** [comment]
Didn't test but might be a reason since vs's <ObjectFileName> setting is started to be used by this PR(#5655). But it solved another problem when we have same file name in different addon. 
So we can not simply roll it back. Pls check discussion in the PR and issue.
Will investigate little more when I have time.

**Comment by arturoc** [comment]
how did you created the projects? I'm testing with a project created with the project generator and that seems to work fine, i can change to any target without having any issue or having to clean

**Comment by arturoc** [comment]
sorry just read that it only happens with addons...

**Comment by arturoc** [comment]
This is fixed now, i've reverted #5655 which was introducing this error and reopened https://github.com/openframeworks/projectGenerator/issues/159 which is a less critical error than this one and was erroneously creating obj files outside the obj folder

**Comment by hiroMTB** [comment]
Thanks!

**Comment by armadillu** [comment]
also see https://github.com/openframeworks/openFrameworks/pull/5655#issuecomment-355404874

**Comment by hiroMTB** [comment]
@arturoc 
Seems like this revert does not solve the critical issue.
Now VS2017 generates .obj file in /bin directory.
And same error because of config mismatch. 
Not sure how it works on VS2015.

**$(IntDir)/$(Platform)/** is working nicer so far. 
It generate all .obj files(including addon related obj) under /myProject/obj/Release/win32 (for examle)
But we don't need to rebuild any config switch of Release|Debug, Win32|x64.

Another temporal option is using "Project Only build", to avoid rebuilding of itself. But if we use addons, for example, openCV, it takes little time to rebuild even with "Project Only Build".

**Comment by arturoc** [comment]
@hiroMTB 
can you send a PR with $(IntDir)/$(Platform) or whatever works best?
