### ISSUE TITLE
Build fails in ARM64EC mode using VS2022

### ISSUE THREAD

**Issue by KawasakiNinjaH2R** [openframeworks/openFrameworks#7789]
Hi all,

I need to build openFrameworks in **arm64ec** mode, this error was reported during compilation: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\include\emmintrin.h(24,1): **error C1189: #error:  this header should only be included through <intrin.h>**

When I modified line 374 of [openframeworks\openFrameworks\libs\glm\include\glm\simd\platform.h](url) to **include <intrin.h>**. can be built successfully. Can you guys help look at this issue? Thanks in advance!

**Reproduction steps:**
1. cd F:\gitP\openframeworks\openFrameworks
2. "C:\Program Files\Git\bin\sh.exe" ./scripts/vs/download_libs.sh -p vs --silent 2>&1
3. set PG_OF_PATH=F:\gitP\openframeworks\openFrameworks
4. F:\gitP\openframeworks\projectGenerator-vs\projectGenerator.exe  ./examples/templates/emptyExample 2>&1
5. F:\gitP\openframeworks\projectGenerator-vs\projectGenerator.exe  ./examples/templates/allAddonsExample 2>&1
6. set _CL_=/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR
7. cd F:\gitP\openframeworks\openFrameworks\build_arm64ec
8. msbuild /m /p:Platform=ARM64EC /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.22618.0 ../libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj /t:Rebuild /p:OutDir=F:\gitP\openframeworks\openFrameworks\build_arm64ec /p:PlatformToolset=v143 > build.log

**Expected result:**
Build successful

**Actual results:**
     1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\include\emmintrin.h(24,1): error C1189: #error:  this header should only be included through <intrin.h> [F:\gitP\openframeworks\openFrameworks\libs\openFrameworksCompiled\project\vs\openframeworksLib.vcxproj]
         (compiling source file '../../../openFrameworks/app/ofAppRunner.cpp')
         
     1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\include\emmintrin.h(24,1): error C1189: #error:  this header should only be included through <intrin.h> [F:\gitP\openframeworks\openFrameworks\libs\openFrameworksCompiled\project\vs\openframeworksLib.vcxproj]
         (compiling source file '../../../openFrameworks/app/ofAppNoWindow.cpp')
         
     1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\include\emmintrin.h(24,1): error C1189: #error:  this header should only be included through <intrin.h> [F:\gitP\openframeworks\openFrameworks\libs\openFrameworksCompiled\project\vs\openframeworksLib.vcxproj]
         (compiling source file '../../../openFrameworks/app/ofAppGLFWWindow.cpp')
         
     1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130\include\emmintrin.h(24,1): error C1189: #error:  this header should only be included through <intrin.h> [F:\gitP\openframeworks\openFrameworks\libs\openFrameworksCompiled\project\vs\openframeworksLib.vcxproj]
         (compiling source file '../../../openFrameworks/3d/of3dUtils.cpp')

**Comment by dimitre** [comment]
Great! do you have a suggestion of Pull Request that not interfere with other platforms?

**Comment by KawasakiNinjaH2R** [comment]
Thank you for your reply! I don't think this change will interfere other platforms.

**Comment by danoli3** [comment]
Could you try with step 2:

"C:\Program Files\Git\bin\sh.exe" ./scripts/vs/download_libs.sh -p vs -b -a
64 --silent 2>&1
Added -b -a 64

Also could try arm64 vs

"C:\Program Files\Git\bin\sh.exe" ./scripts/vs/download_libs.sh -p vs -b -a
arm64 --silent 2>&1

**Comment by ofTheo** [comment]
@danoli3 I believe we are not currently building libs for 64bit arm for VS ( I know you are working on this for bleeding ) but I think the only libs available for VS are x86_64 

@KawasakiNinjaH2R I wonder if you add `#include <intrin.h>`  to this line does that solve it for you?
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofConstants.h#L146

**Comment by KawasakiNinjaH2R** [comment]
Hi guys, thanks for all the replies.


@danoli3, I tried the two commands you gave, but unfortunately they both failed. The downloaded compressed folder is empty. The error message is as follows:
In addition, I would like to add that I can compile it successfully under x64 architecture using vs. Only if the compilation fails under the arm64ec architecture
```
 Connection #0 to host github.com left intact

Warning: Got more output options than URLs
Removing old libraries
Uncompressing libraries vsarm64 from openFrameworksLibs_master_vs_arm64_1.zip
[../scripts/dev/openFrameworksLibs_master_vs_arm64_1.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ../scripts/dev/openFrameworksLibs_master_vs_arm64_1.zip or
        ../scripts/dev/openFrameworksLibs_master_vs_arm64_1.zip.zip, and cannot find ../scripts/dev/openFrameworksLibs_master_vs_arm64_1.zip.ZIP, period.
Error on or near line 212; exiting with status 1

```

@ofTheo , I tried adding #include <intrin.h> to the location you mentioned, but the error still occurred.

**Comment by danoli3** [comment]
Ah this should be almost fixed now with new libs. 

Where you also linking against OpenCV? 

I was able to fix and recompile it without instincts on via Cmake option and looks like it solves it

**Comment by KawasakiNinjaH2R** [comment]
@danoli3 No, I did not link against OpenCV.

**Comment by danoli3** [comment]
I am not currently experiencing the intrinsic issue however I do have a stack of CRT and DLL things to fix, so maybe it's beyond the next mountain.

With ARM64EC, since its a magical hybrid x64 / ARM64 for Windows 11 exclusively, make sure you are linking to that 11 SDK 10.0.20348

Good timing for your post though as I have no successfully toolchained and setup ARM64EC for native builds of all dependencies using the new cmake system with `cmake .. -B . --preset arm64ec ` and targetting SDK for those libs to Win 11

**Comment by danoli3** [comment]
Yeah it was much deeper than a preset file.

Basically this instinct error or warning is the ARM CPU does not have SIMP optimisations, so the counter of course is NEON.
Now Android we know about NEON however for MSVC didn't think about it. 

https://developer.arm.com/architectures/instruction-sets/intrinsics/

So i've found Microsoft have added Neon just recently to 17.8: 
https://learn.microsoft.com/en-us/cpp/intrinsics/arm64-intrinsics?view=msvc-170

So good news then I think maybe we could just include the MVSC Neon include and it be all sweet. 

I've written a SIMD header finder in grep and currently analysing dependency and core. 

In the current headers and core we have the following:
```
addons/ofxOpenCv/libs/opencv/include/opencv2/core/fast_math.hpp:73:    #include <emmintrin.h>
Searching for immintrin.h libs/glm/include/glm/detail/func_common_simd.inl:8:#include <immintrin.h>
Searching for arm_neon.h in libs/glm/include/glm/simd/neon.h:7:#include <arm_neon.h>
Finished
```

Each location will need to checked and defined correctly for ARM targets on Windows.

**Comment by KawasakiNinjaH2R** [comment]
Hi @danoli3 , thank you for your reply. I tried to use the latest commit, but the build still failed. Maybe I need to wait a little longer?

**Comment by danoli3** [comment]
Yeah just fixing up dependency libs where using this in the core libs/headers currently see:
https://github.com/openframeworks/apothecary/issues/322

**Comment by KawasakiNinjaH2R** [comment]
Thank you for your help.

**Comment by danoli3** [comment]
Updated if you have any more issues @KawasakiNinjaH2R let me know!

Further tests information here: https://github.com/openframeworks/openFrameworks/issues/8015
